name: wsi-ssrl
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.9.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - blas=2.131
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - debugpy=1.8.11
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - fontconfig=2.14.1
  - fonttools=4.58.0
  - fqdn=1.5.1
  - freetype=2.10.4
  - gdk-pixbuf=2.42.10
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.36.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - json5=0.12.0
  - jsonpointer=2.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.15
  - lerc=4.0.0
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.4
  - libdeflate=1.22
  - libedit=3.1.20191231
  - libexpat=2.7.0
  - libffi=3.4.4
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libiconv=1.18
  - libintl=0.24.1
  - libintl-devel=0.24.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libsodium=1.0.20
  - libsqlite=3.46.0
  - libtiff=4.5.1
  - libwebp-base=1.5.0
  - libxml2=2.13.8
  - libxslt=1.1.41
  - libzlib=1.2.13
  - llvm-openmp=20.1.4
  - lxml=5.3.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openblas=0.3.29
  - openjdk=21.0.6
  - openjpeg=2.5.0
  - openslide=3.4.1
  - openslide-python=1.3.1
  - openssl=3.5.0
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=25.1
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.51
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pyobjc-core=10.1
  - pyobjc-framework-cocoa=10.1
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - send2trash=1.8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.7
  - sqlite=3.45.3
  - stack_data=0.6.3
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.4.2
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.6
  - pip:
      - filelock==3.18.0
      - fsspec==2025.3.2
      - imageio==2.37.0
      - joblib==1.5.0
      - lazy-loader==0.4
      - mpmath==1.3.0
      - networkx==3.4.2
      - opencv-python==4.11.0.86
      - pandas==2.2.3
      - python-dotenv==1.1.0
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - sqlalchemy==2.0.40
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - torch==2.7.0
      - torchvision==0.22.0
      - tzdata==2025.2
