# =============================================================================
# RCC_WSIs preprocessing configuration
# =============================================================================

# -----------------------------------------------------------------------------#
# Raw data paths                                                               #
# -----------------------------------------------------------------------------#
# WARNING: include spaces in the path exactly as they appear on disk.
# If using Linux you may need to replace "Il mio Drive" with "My Drive".
# -----------------------------------------------------------------------------#
base_dir: "~/Library/CloudStorage/GoogleDrive-stefano2001roy@gmail.com/Il mio Drive/Colab_Notebooks/wsi-ssrl-rcc_project/data/RCC_WSIs"
paths:
  # ------------ ccRCC / pRCC (WSI .scn + annotations .xml) -------------------
  ccrcc_wsi:       "${base_dir}/ccRCC"
  ccrcc_xml:       "${base_dir}/ccRCC/ccRCC_xml"
  prcc_wsi:        "${base_dir}/pRCC"
  prcc_xml:        "${base_dir}/pRCC/pRCC_xml"
  pre_ccrcc_wsi:   "${base_dir}/pre/ccRCC"
  pre_ccrcc_xml:   "${base_dir}/pre/ccRCC/pre_ccRCC_xml"
  pre_prcc_wsi:    "${base_dir}/pre/pRCC"
  pre_prcc_xml:    "${base_dir}/pre/pRCC/pre_pRCC_xml"

  # ------------ CHROMO / ONCO (WSI .svs + ROI .svs/.tif) ---------------------
  chromo_wsi:      "${base_dir}/CHROMO"
  onco_wsi:        "${base_dir}/ONCOCYTOMA"
  chromo_ann:      "${base_dir}/Annotations_chromo"
  onco_ann:        "${base_dir}/Annotations_onco"

# -----------------------------------------------------------------------------#
# Train/val/test splits by patient                                            #
# -----------------------------------------------------------------------------#
split_json: "data/processed/splits_by_patient.json"

# -----------------------------------------------------------------------------#
# Quick reduction for debugging (true ⇒ n patients per class)                  #
# -----------------------------------------------------------------------------#
downsample_patients:
  enabled: true
  per_class: 5

# =============================================================================
# Patching configuration
# =============================================================================

patching: