
# =============================================================================
# Modelli: configurazioni specifiche per SSL e CNN                             
# =============================================================================
models:

  simclr:
    backbone: "resnet50"
    proj_dim: 128
    augmentation:
      enabled: true
      horizontal_flip: true
      rotation: [0, 90, 180, 270]
      color_jitter:
        brightness: 0.5
        contrast:   0.5
        saturation: 0.5
        hue:        0.2
    training:
      epochs:          100
      batch_size:      256
      optimizer:       "adam"
      learning_rate:   1e-3
      weight_decay:    1e-6
      temperature:     0.5

  moco_v2:
    backbone: "resnet50"
    proj_dim:  128
    augmentation:
      enabled:      true
      horizontal_flip: true
      color_jitter:
        brightness: 0.4
        contrast:   0.4
        saturation: 0.4
        hue:        0.1
      gaussian_blur: true
      grayscale:     true
    training:
      epochs:          200
      batch_size:      256
      optimizer:       "sgd"
      learning_rate:   0.03
      weight_decay:    1e-4
      queue:           65536
      m:               0.99
      temperature:     0.07

  rotation:
    backbone: "resnet18"
    training:
      epochs:        50
      batch_size:    128
      optimizer:     "adam"
      learning_rate: 1e-4
      weight_decay:  1e-5

  jigsaw:
    backbone:  "resnet18"
    grid_size: 3
    training:
      epochs:        50
      batch_size:    128
      optimizer:     "adam"
      learning_rate: 1e-4
      weight_decay:  1e-5

  supervised:
    backbone:   "resnet50"
    pretrained: false
    training:
      epochs:        50
      batch_size:    32
      optimizer:     "adam"
      learning_rate: 1e-4
      weight_decay:  1e-5

  transfer:
    backbone:   "resnet50"
    pretrained: true
    training:
      epochs:        50
      batch_size:    32
      optimizer:     "adam"
      learning_rate: 1e-4
      weight_decay:  1e-5
