# config/training_colab.yaml

# -----------------------------------------------------------------------------#
# Environment detection                                                         
# -----------------------------------------------------------------------------#
env_paths:
  colab: "/content/drive/MyDrive/Colab Notebooks/MLA_PROJECT/wsi-ssrl-rcc_project"
  local: "/Users/mimmo/Desktop/mimmo/MLA/project_FP03/wsi-ssrl-rcc_project"

# -----------------------------------------------------------------------------#
# Quale modello lanciare                                                        
# -----------------------------------------------------------------------------#
run_model: all  # es. simclr, supervised o all

# -----------------------------------------------------------------------------#
# Percorsi relativi ai WebDataset                                              
# -----------------------------------------------------------------------------#
data:
  train: "data/processed/webdataset_2500/train/patches-0000.tar"
  val:   "data/processed/webdataset_2500/val/patches-0000.tar"
  test:  "data/processed/webdataset_2500/test/patches-0000.tar"

# -----------------------------------------------------------------------------#
# Parametri di tutti i modelli                                                 
# -----------------------------------------------------------------------------#
models:
  simclr:
      backbone: "resnet18"
      proj_dim: 128
      augmentation:
        enabled: true
        horizontal_flip: true
        rotation: [0, 90, 180, 270]
        color_jitter:
          brightness: 0.5
          contrast:   0.5
          saturation: 0.5
          hue:        0.2
      training:
        epochs:          50
        batch_size:      64
        optimizer:       "adam"
        learning_rate:   1e-3
        weight_decay:    1e-6
        temperature:     0.5
  moco_v2:
    backbone: "resnet18"
    proj_dim:  128
    augmentation:
      enabled:        true
      horizontal_flip: true
      color_jitter:
        brightness: 0.4
        contrast:   0.4
        saturation: 0.4
        hue:        0.1
      gaussian_blur:  true
      grayscale:      true
    training:
      epochs:        2
      batch_size:    128
      optimizer:     "sgd"
      learning_rate: 0.03
      weight_decay:  1e-4
      queue:         65536
      m:             0.99
      temperature:   0.07

  rotation:
    backbone: "resnet18"
    training:
      epochs:        2
      batch_size:    64
      optimizer:     "adam"
      learning_rate: 1e-4
      weight_decay:  1e-5

  jigsaw:
    backbone:  "resnet18"
    grid_size: 3
    training:
      epochs:        2
      batch_size:    64
      optimizer:     "adam"
      learning_rate: 1e-4
      weight_decay:  1e-5

  supervised:
    backbone:   "resnet50"
    pretrained: false
    training:
      epochs:        50
      batch_size:    64
      optimizer:     "adam"
      learning_rate: 1e-4
      weight_decay:  1e-5

  transfer:
    backbone:   "resnet50"
    pretrained: true
    training:
      epochs:        2
      batch_size:    64
      optimizer:     "adam"
      learning_rate: 1e-4
      weight_decay:  1e-5
